### Instructions

* **Kernel:** the shared repo-root `.venv` (same kernel as every Day 1 notebook).
* **AI-Free Zone:** write the code yourself.
* Download the Yellow Taxi data for January 2026 from the official TLC page (https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page), or directly from the TLC CDN. From your work folder:

**Note** The data is made available to you in 'data/yellow_tripdata_2026-01.parquet'

* This is about 64.2 MB and 3.7 million rows: your first realistically sized file in this course.
* Use pandas to inspect the data and perform the transformations below. The expected outputs are shown after several cells so you can check yourself.
* Finally, write the output as a partitioned parquet file.

> **pandas 3 note:** the embedded outputs in this notebook were captured on an older pandas. Two harmless differences you may see today: text columns show dtype `str` instead of `object`, and `SettingWithCopyWarning` no longer exists (pandas 3 uses Copy-on-Write instead).

In [1]:
import pandas as pd
from pathlib import Path

In [ ]:
# read the file you downloaded to yellow_tripdata_2024-04.parquet
import pandas as pd

DATA_PATH = #TODO
OUT_DIR = #TODO

In [ ]:
# inspect few records

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.90,1.0,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.40,1.0,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0.0,2.16,1.0,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1.0,23.10,2.5,0.0,0.75

In [ ]:
# inspect size

(3724889, 20)

In [ ]:
# inspect the data

<class 'pandas.DataFrame'>
RangeIndex: 3724889 entries, 0 to 3724888
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), str(1)
memory usage: 528.5 MB

In [ ]:
# calculate Trip Duration in Minutes. Call it Trip_Duration. Check out how the results look like in below cells.


df[['Trip_Duration']].head()

   Trip_Duration
0            5.0
1            5.0
2            8.0
3           42.0
4           13.0

In [ ]:
# Calculate Total Trip Charge to inclide: fare amount, extra, mta_tax, tolls amount, improvement surcharge, congestion surcharge, airport fee, and tip amount
# CAll it Total_Trip_Charge



df[['Total_Trip_Charge']].head()

   Total_Trip_Charge
0              15.86
1              16.15
2              21.45
3              54.81
4              22.35

In [ ]:
# What is the most common passenger count?

passenger_count
1.0    2150994
2.0     334370
3.0      72864
4.0      49738
0.0      14787
5.0       9184
6.0       4887
8.0          4
7.0          2
9.0          1
Name: count, dtype: int64

In [11]:
# Add Trip Date, Trip Month Name, Trip Day Name, and Trip Year
# call them Trip_Date, Trip_Month, Trip_Day, and Trip_Year

In [10]:
# this is how the data looks like now
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,Trip_Duration,Total_Trip_Charge,Trip_Date,Trip_Month,Trip_Day,Trip_Year
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,...,15.86,2.5,0.0,0.00,5.0,15.86,2026-01-01,January,Thursday,2026
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.90,1.0,N,163,162,2,...,13.65,2.5,0.0,0.75,5.0,16.15,2026-01-01,January,Thursday,2026
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.40,1.0,N,43,237,1,...,18.95,2.5,0.0,0.75,8.0,21.45,2026-01-01,January,Thursday,2026
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,...,55.56,2.5,0.0,0.75,42.0,54.81,2026-01-01,January,Thursday,2026
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0.0,2.16,1.0,N,88,144,1,...,23.10,2.5,0.0,0.75,13.0,22.35,2026-01-01,January,Thursday,2026

In [ ]:
# inspect memory used

Index                         132
VendorID                 14899556
tpep_pickup_datetime     29799112
tpep_dropoff_datetime    29799112
passenger_count          29799112
trip_distance            29799112
RatecodeID               29799112
store_and_fwd_flag       32639411
PULocationID             14899556
DOLocationID             14899556
payment_type             29799112
fare_amount              29799112
extra                    29799112
mta_tax                  29799112
tip_amount               29799112
tolls_amount             29799112
improvement_surcharge    29799112
total_amount             29799112
congestion_surcharge     29799112
Airport_fee              29799112
cbd_congestion_fee       29799112
Trip_Duration            29799112
Total_Trip_Charge        29799112
Trip_Date                29799112
Trip_Month               55873342
Trip_Day                 56803857
Trip_Year                14899556
dtype: int64

In [ ]:
# Total memory used
total_bytes = # TODO
print(f"{total_bytes / 1024**2:.2f} MB")   
print(f"{total_bytes / 1024**3:.2f} GB")

735.38 MB
0.72 GB

In [ ]:
# inspect DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 3724889 entries, 0 to 3724888
Data columns (total 26 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
 20  Trip_Duration          float64
 21  Total_Trip_Charge      float64
 22  Trip_Date              datetime64[s]
 23  Trip_Month             str
 24  Trip_Day               str
 25  Trip_Year              int32
dtypes: datetime64[s](1), datetime64[us](2), float64(15), int32(4), int64(1), str(3)
memory usage: 735.4 MB

In [ ]:
# list existing columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee', 'Trip_Duration', 'Total_Trip_Charge', 'Trip_Date',
       'Trip_Month', 'Trip_Day', 'Trip_Year'],
      dtype='str')

In [ ]:
# keep only specific columns 
# 'VendorID', 'passenger_count', 'trip_distance', 'store_and_fwd_flag', 'payment_type', 'Trip_Duration', 'Total_Trip_Charge', 'Trip_Date', 'Trip_Month', 'Trip_Year', 'Trip_Day'

# Reorder the columns, starting with Vendor ID, followed by all the different date/time columns example Date, Year, Month, and Day, then followed by the remaining columns 

cols = #TODO

df = df[cols]

In [17]:
# inspect the latest DataFrame 
df.head()

,VendorID,Trip_Date,Trip_Year,Trip_Month,Trip_Day,passenger_count,trip_distance,store_and_fwd_flag,payment_type,Trip_Duration,Total_Trip_Charge
0,2,2026-01-01,2026,January,Thursday,1.0,0.97,N,1,5.0,15.86
1,1,2026-01-01,2026,January,Thursday,0.0,0.90,N,2,5.0,16.15
2,1,2026-01-01,2026,January,Thursday,0.0,1.40,N,1,8.0,21.45
3,2,2026-01-01,2026,January,Thursday,4.0,5.58,N,1,42.0,54.81
4,2,2026-01-01,2026,January,Thursday,0.0,2.16,N,1,13.0,22.35

Rename the columns:
* `VendorID` to `Vendor_ID`
* `passenger_count` to `No_of_Passengers`
* `store_and_fwd_flag` to `SF_Flag`
* `payment_type` to `Payment_Type`

In [ ]:
# Rename the columns - see the output below
df = #TODO
df.head()

,Vendor_ID,Trip_Date,Trip_Year,Trip_Month,Trip_Day,No_of_Passengers,trip_distance,SF_Flag,Payment_Type,Trip_Duration,Total_Trip_Charge
0,2,2026-01-01,2026,January,Thursday,1.0,0.97,N,1,5.0,15.86
1,1,2026-01-01,2026,January,Thursday,0.0,0.90,N,2,5.0,16.15
2,1,2026-01-01,2026,January,Thursday,0.0,1.40,N,1,8.0,21.45
3,2,2026-01-01,2026,January,Thursday,4.0,5.58,N,1,42.0,54.81
4,2,2026-01-01,2026,January,Thursday,0.0,2.16,N,1,13.0,22.35

In [ ]:
# Save as Parquet parition by Year, Month. You can call it 'Yellow Taxi Transformed'
# Hint: Use the OUT_DIR variable defined at the top of this notebook to save the file in the same directory as the original file.
# Hint: As an Example Your output should look like: 'outputs/Yellow_Taxi_Transformed/Trip_Year=2026/Trip_Month=January

**Challenge 1**

* Inspect the Parquet folder, look at the partitions. Is there someting strange? Yes/No
* If Yes. Find which rows are causing this and capture them
* What do you think happened?

In [ ]:
#TODO

Trip_Year=2025
Trip_Year=2026